[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "30s"
# Needed because on macOS there are no prebuilt binaries for Node <15. Requires mise 2024.12.7+.
MISE_ARCH="x86_64"

[tools]
node = "14.21.3"
yarn = "3.2.1"
python = "3.11"

[tasks.build]
run = 'yarn && yarn install && yarn build'

[tasks.test]
depends = ['build']

run = 'yarn test'

[tasks.lint]
run = 'yarn lint'

[tasks.pack]
description = 'Build packages locally, for local testing'
depends = ['build']

run = [
    'npm run core pack',
    'npm run browser pack',
    'npm run node pack',
    'ls -lat packages/*/package.tgz'
]

[tasks.clean]
description = 'Remove build artifacts'
run = 'npm run clean'
